blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: https://github.com/BBS-Lab/nova-toast/discussions
    about: Ask and answer questions about this package.
  - name: 🔒 Report a security issue
    url: https://github.com/BBS-Lab/nova-toast/security/policy
    about: Please report security vulnerabilities privately.
